# Generated by Django 5.0.4 on 2025-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_category', models.CharField(max_length=100)),
                ('dish_description', models.CharField(max_length=500)),
                ('offer_price', models.CharField(max_length=15)),
                ('actual_price', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'adddishes',
            },
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.CharField(max_length=15)),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_price', models.CharField(max_length=15)),
                ('quantity', models.CharField(max_length=15)),
                ('total_pr', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bag',
            },
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('total_dishes', models.CharField(max_length=100)),
                ('total_pr', models.CharField(max_length=15)),
                ('payment', models.CharField(max_length=15)),
                ('card_number', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=15)),
                ('expiry_date', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('confirm_password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
